Repository vincentrohde/iot_app, pull requests merged in 2019-02, with the labels that each got.

#3 add AddButton
  src/components/AddButton/AddButton.js
  src/components/AddButton/AddButton.scss
  src/components/App.js
  src/components/Example/Example.js
Labels: review required

#7 add IntroPage
  src/routers/AppRouter.js
  src/routes/IntroPage/IntroPage.js
Labels: review required

#11 Link CTAButton to HomePage
  src/components/CTAButton/CTAButton.js
  src/components/CTAButton/CTAButton.scss
Labels: review required

#17 add container margin and styles to Navigation
  src/assets/images/avatar.png
  src/components/AvatarIcon/AvatarIcon.js
  src/components/AvatarIcon/AvatarIcon.scss
  src/components/Headline/Headline.js
  src/components/Navigation/Navigation.scss
  src/routes/Dashboard/Dashboard.js
  src/routes/Page.scss
Labels: review required

#19 Fixes/add button
  src/components/AddButton/AddButton.js
  src/components/AddButton/AddButton.scss
Labels: review required

#31 [Feature] add props to Headline, Lane and AddButton
  src/components/AddButton/AddButton.js
  src/components/Headline/Headline.js
  src/components/Lane/Lane.js
Labels: feature, review required

#16 Styling IntroPage
  src/components/AddButton/AddButton.scss
  src/index.scss
  src/routes/IntroPage/IntroPage.js
  src/routes/IntroPage/IntroPage.scss
Labels: coding standards

#40 added .wavy-background in the index.scss and in the introPage
  src/assets/images/wave.svg
  src/index.scss
  src/routes/IntroPage/IntroPage.js
  src/routes/IntroPage/IntroPage.scss
Labels: coding standards

#44 Added add-button.svg, centered the button in the container
  src/assets/images/add-button.svg
  src/components/AddButton/AddButton.js
  src/components/AddButton/AddButton.scss
  src/components/OrderLane/OrderLane.scss
Labels: coding standards

#33 [style] Feature/dashboard
  src/components/Lane/Lane.scss
  src/components/Room/Room.js
  src/components/Room/Room.scss
  src/components/Rooms/Rooms.js
  src/routes/Dashboard/Dashboard.js
  src/routes/Dashboard/Dashboard.scss
  src/scss/variables.scss
Labels: coding standards

#48 added .wavy-gradient to the Dashboard
  src/routes/Dashboard/Dashboard.js
  src/routes/Dashboard/Dashboard.scss
Labels: bug

#59 add target WebSocket to Sideboard
  src/components/Sideboard/Sideboard.js
Labels: review required

#69 add Login form to intro page
  src/components/Login/Login.js
  src/components/Login/Login.scss
  src/routes/IntroPage/IntroPage.js
  src/routes/IntroPage/IntroPage.scss
Labels: question, review required
